[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = [
  "npm ci --omit=optional",
  "npm install @rollup/rollup-linux-x64-musl --no-save --ignore-engines",
  "cd backend && npm ci --omit=optional"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "cd backend && node src/server.js" 